### ISSUE TITLE
figure out what "hyeeneffect1" does, and get it to work

### ISSUE THREAD

**Issue by hyenatown** [hyenatown/starbound-hyena-race#1]
Seems like there's a stock status effect included with Skittles' character template named [race]effect1.statuseffect, but there's not really much to say about it because it's incomplete - no way to invoke it automatically, which might require a script of some sort.

**Comment by AmpYeen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [hyeeneffect1 is weird](https://trello.com/c/3CpoUrj4/47-hyeeneffect1-is-weird)

**Comment by hyenatown** [comment]
Figured it out, finally. After a single grep, I found it was part of the kitty cosmetic.
